### ISSUE TITLE
After selecting quality profile, does not proceed.

### ISSUE THREAD

**Issue by cryptofyre** [kiranshila/Doplarr#117]
**Describe the bug**
While selecting and going through the normal bot process, it will consistently get stuck on the quality profile and not allow the user to continue. 

**Expected behavior**
It should move on to the next step.

**Screenshots**
![image](https://user-images.githubusercontent.com/33162551/215624228-3bfe1c62-e664-469f-a85b-42c6fbe36322.png)

**Logs**
Please copy out the log in it's entirety, please make sure to hide any potential secrets/API keys - although they should be censored via the logging program.
```
2023-01-31T00:00:10.348Z 0b6e661dd22d TRACE [discljord.messaging.impl:?] - Got event [{:discljord.messaging.specs/action :create-interaction-response} #object[discljord.util.DerefablePromiseChannel 27e8745e "discljord.util.DerefablePromiseChannel@27e8745e"] 1069769022452809789 aW50ZXJhY3Rpb246MTA2OTc2OTAyMjQ1MjgwOTc4OToxa1BsU3pvdjVwQ3BySVlDc2VxdEJBR2traElFeURDd1VpTGZOZEVQaWNBTlpLbTZqQnI0TThUaEJGbmw4R3F3MGU3M2FiUjFhdW5OOXRDclh5MFpQampPSjRaZktWZmE5amFaWVl6ZkdwV0czeDIwUGJPNkFqTVlHUlRoS2prUA 6 :user-agent nil :audit-reason nil]
2023-01-31T00:00:10.348Z 0b6e661dd22d TRACE [discljord.messaging.impl:?] - Stepping agent with process {:discljord.messaging.specs/rate-limits #object[clojure.lang.Atom 0x24a31924 {:status :ready, :val {a3b974ef6eb1c925dd4ceb42f4db26fd {nil {:discljord.messaging.specs/rate 2, :discljord.messaging.specs/remaining 1, :discljord.messaging.specs/reset 1675122606437}}, 3d2712a9e4fe17cc9d3fed4a8e672e5f {{:discljord.messaging.specs/major-variable-value aW50ZXJhY3Rpb246MTA2OTc2NjQ4MjI1NjQ2NTk1MDpjdjdUTlh3M2Z1bW9QNzd5cVZ5MGpNS0RyTmM5bUo0MnNyVDZVT01ueEx4TXpoMmwwUlM5TzI2czRsSlVmemZvZldjUkZrTGV0Y25Sa1Z5RnRmajZzM0NtVVZkZHdaNGx6bHdHbTJKdlFsWjM0NGVIUG4xVVE5WlE5eklNY1pWYw, :discljord.messaging.specs/major-variable-type :discljord.messaging.specs/interaction-token} {:discljord.messaging.specs/rate 5, :discljord.messaging.specs/remaining 4, :discljord.messaging.specs/reset 1675122624017}, {:discljord.messaging.specs/major-variable-value aW50ZXJhY3Rpb246MTA2OTc2NzcxNDAwMTkxNTkzNDp0Z2NtN29hVXBjMGlueE5qRUt5QnBjeXdpWUNIR3MxRnE2TnU4UlZKUnNieXZhVU5ESlJuak1JRmRIZ1hFd1JQaHBSdXZSU3NCcXFBekVQdXBSbTJFamRIb3NTdllZR1p5S2pnV0lNekpRRGRFbm10aTNic3FiWEJabmhwWUlvWA, :discljord.messaging.specs/major-variable-type :discljord.messaging.specs/interaction-token} {:discljord.messaging.specs/rate 5, :discljord.messaging.specs/remaining 4, :discljord.messaging.specs/reset 1675122914934}}}}], :discljord.messaging.specs/endpoint-agents {{:discljord.messaging.specs/action :bulk-overwrite-guild-application-commands} #object[clojure.lang.Agent 0x45b91805 {:status :ready, :val a3b974ef6eb1c925dd4ceb42f4db26fd}], {:discljord.messaging.specs/action :create-interaction-response} #object[clojure.lang.Agent 0x3f100e0b {:status :ready, :val nil}], {:discljord.messaging.specs/action :edit-original-interaction-response, :discljord.messaging.specs/major-variable {:discljord.messaging.specs/major-variable-value aW50ZXJhY3Rpb246MTA2OTc2NjQ4MjI1NjQ2NTk1MDpjdjdUTlh3M2Z1bW9QNzd5cVZ5MGpNS0RyTmM5bUo0MnNyVDZVT01ueEx4TXpoMmwwUlM5TzI2czRsSlVmemZvZldjUkZrTGV0Y25Sa1Z5RnRmajZzM0NtVVZkZHdaNGx6bHdHbTJKdlFsWjM0NGVIUG4xVVE5WlE5eklNY1pWYw, :discljord.messaging.specs/major-variable-type :discljord.messaging.specs/interaction-token}} #object[clojure.lang.Agent 0x115aa85b {:status :ready, :val 3d2712a9e4fe17cc9d3fed4a8e672e5f}], {:discljord.messaging.specs/action :edit-original-interaction-response, :discljord.messaging.specs/major-variable {:discljord.messaging.specs/major-variable-value aW50ZXJhY3Rpb246MTA2OTc2NzcxNDAwMTkxNTkzNDp0Z2NtN29hVXBjMGlueE5qRUt5QnBjeXdpWUNIR3MxRnE2TnU4UlZKUnNieXZhVU5ESlJuak1JRmRIZ1hFd1JQaHBSdXZSU3NCcXFBekVQdXBSbTJFamRIb3NTdllZR1p5S2pnV0lNekpRRGRFbm10aTNic3FiWEJabmhwWUlvWA, :discljord.messaging.specs/major-variable-type :discljord.messaging.specs/interaction-token}} #object[clojure.lang.Agent 0x3187f918 {:status :ready, :val 3d2712a9e4fe17cc9d3fed4a8e672e5f}]}, :discljord.specs/channel #object[clojure.core.async.impl.channels.ManyToManyChannel 0x6fcdc1a8 clojure.core.async.impl.channels.ManyToManyChannel@6fcdc1a8], :discljord.specs/token Bot MTA2OTcyMDU5MjUxOTAwODMzNw.G9j0Ra.IxLJNuaoCvEWiv9EnW8FjzBdFuNTO7-5ZlnuxA, :discljord.messaging.specs/global-limit #object[clojure.lang.Atom 0x4b3d3e64 {:status :ready, :val nil}]}
2023-01-31T00:00:10.348Z 0b6e661dd22d TRACE [discljord.messaging.impl:?] - Making request to endpoint {:discljord.messaging.specs/action :create-interaction-response}
2023-01-31T00:00:10.348Z 0b6e661dd22d TRACE [discljord.messaging.impl:?] - Making request
Exception in thread "async-dispatch-10" java.lang.IndexOutOfBoundsException
2023-01-31T00:00:10.570Z 0b6e661dd22d TRACE [discljord.messaging.impl:?] - Got response from request {:opts {:query-params nil, :headers {Authorization Bot MTA2OTcyMDU5MjUxOTAwODMzNw.G9j0Ra.IxLJNuaoCvEWiv9EnW8FjzBdFuNTO7-5ZlnuxA, User-Agent DiscordBot (https://github.com/discljord/discljord, 1.3.1) , Content-Type multipart/form-data}, :multipart [{:name payload_json, :content {"audit_reason":null,"type":6}}], :method :post, :url https://discord.com/api/v9/interactions/1069769022452809789/aW50ZXJhY3Rpb246MTA2OTc2OTAyMjQ1MjgwOTc4OToxa1BsU3pvdjVwQ3BySVlDc2VxdEJBR2traElFeURDd1VpTGZOZEVQaWNBTlpLbTZqQnI0TThUaEJGbmw4R3F3MGU3M2FiUjFhdW5OOXRDclh5MFpQampPSjRaZktWZmE5amFaWVl6ZkdwV0czeDIwUGJPNkFqTVlHUlRoS2prUA/callback}, :body , :headers {:date Tue, 31 Jan 2023 00:00:10 GMT, :x-content-type-options nosniff, :via 1.1 google, :server cloudflare, :report-to {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=e1knRny27gz60nPI6Idyunxa9G1Q%2FoOtLxXl1yeaclXcj7kUrtQSBQNiC7U4DPsX7aqEIQbKXwAP%2Fbz02GETgJPwTxw5HSqGtqKNZBKz7i34AuZEsYn4pZmXARSM"}],"group":"cf-nel","max_age":604800}, :cf-ray 791e2a613d66e8ed-DFW, :strict-transport-security max-age=31536000; includeSubDomains; preload, :alt-svc h3=":443"; ma=86400, h3-29=":443"; ma=86400, :content-type text/html; charset=utf-8, :cf-cache-status DYNAMIC, :connection keep-alive, :nel {"success_fraction":0,"report_to":"cf-nel","max_age":604800}, :set-cookie __dcfduid=3ab2c068a0fa11ed8c0f2ab59eeb4cc6; Expires=Sun, 30-Jan-2028 00:00:10 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/,__sdcfduid=3ab2c068a0fa11ed8c0f2ab59eeb4cc6bfd18ea3069b406d0c48e1c71e5a8a87d2d95b5355763e17d7621c2a627fbd34; Expires=Sun, 30-Jan-2028 00:00:10 GMT; Max-Age=157680000; Secure; HttpOnly; Path=/,__cfruid=3ebef6768fdd0c9dc4aaabdff761da82aea0c78a-1675123210; path=/; domain=.discord.com; HttpOnly; Secure; SameSite=None}, :status 204}
        at clojure.lang.RT.nthFrom(RT.java:928)
        at clojure.lang.RT.nth(RT.java:897)
        at doplarr.discord$option_dropdown.invokeStatic(discord.clj:102)
        at doplarr.discord$option_dropdown.invoke(discord.clj:97)
        at doplarr.interaction_state_machine$query_for_option_or_request$fn__23984$state_machine__5617__auto____23989$fn__23992.invoke(interaction_state_machine.clj:55)
        at doplarr.interaction_state_machine$query_for_option_or_request$fn__23984$state_machine__5617__auto____23989.invoke(interaction_state_machine.clj:44)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at doplarr.interaction_state_machine$query_for_option_or_request$fn__23984.invoke(interaction_state_machine.clj:44)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__361$fn__362.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Additional context**
I'm using Discord roles and Unraid to host this combined with Sonarr.

**Comment by jonnywright** [comment]
Same issue here

```
doplarr      | Exception in thread "async-dispatch-12" java.lang.IndexOutOfBoundsException
doplarr      |  at clojure.lang.RT.nthFrom(RT.java:928)
doplarr      |  at clojure.lang.RT.nth(RT.java:897)
doplarr      |  at doplarr.discord$option_dropdown.invokeStatic(discord.clj:102)
doplarr      |  at doplarr.discord$option_dropdown.invoke(discord.clj:97)
doplarr      |  at doplarr.interaction_state_machine$query_for_option_or_request$fn__23984$state_machine__5617__auto____23989$fn__23992.invoke(interaction_state_machine.clj:55)
doplarr      |  at doplarr.interaction_state_machine$query_for_option_or_request$fn__23984$state_machine__5617__auto____23989.invoke(interaction_state_machine.clj:44)
doplarr      |  at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
doplarr      |  at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
doplarr      |  at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
doplarr      |  at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
doplarr      |  at doplarr.interaction_state_machine$query_for_option_or_request$fn__23984.invoke(interaction_state_machine.clj:44)
doplarr      |  at clojure.lang.AFn.run(AFn.java:22)
doplarr      |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
doplarr      |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
doplarr      |  at clojure.core.async.impl.concurrent$counted_thread_factory$reify__361$fn__362.invoke(concurrent.clj:29)
doplarr      |  at clojure.lang.AFn.run(AFn.java:22)
doplarr      |  at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by wbsmolen** [comment]
Also hitting this issue

**Comment by wbsmolen** [comment]
@cryptofyre your sonarr/radarr configs dont have root folders set
