### ISSUE TITLE
Sometimes Profile ID is 0

### ISSUE THREAD

**Issue by kiranshila** [kiranshila/Doplarr#33]
Seen with requests through Sonarr

```clj
Exception in thread "async-dispatch-1" clojure.lang.ExceptionInfo: Non 403 error on request {:request-time 74, :request {:user-info nil, :as :json, :headers {"X-API-Key" "898a124b1af34259b0174618527416c0", "content-type" "application/json", "accept-encoding" "gzip, deflate"}, :server-port 8989, :url "http://localhost:8989/api/series", :content-type "application/json", :http-request #object[jdk.internal.net.http.HttpRequestImpl 0xcd30d4b "http://localhost:8989/api/series POST"], :uri "/api/series", :server-name "localhost", :query-string nil, :body "{\"tags\":[],\"seasonFolder\":true,\"imdbId\":\"tt8042500\",\"languageProfileId\":0,\"qualityProfileId\":0,\"sortTitle\":\"y last man\",\"images\":[{\"coverType\":\"banner\",\"url\":\"https://artworks.thetvdb.com/banners/v4/series/362250/banners/61376b12a3091.jpg\"},{\"coverType\":\"poster\",\"url\":\"https://artworks.thetvdb.com/banners/v4/series/362250/posters/611f995929dd5.jpg\"},{\"coverType\":\"fanart\",\"url\":\"https://artworks.thetvdb.com/banners/v4/series/362250/backgrounds/6116c9489ad4b.jpg\"}],\"added\":\"0001-01-01T00:00:00Z\",\"cleanTitle\":\"ylastman\",\"firstAired\":\"2021-09-13T00:00:00Z\",\"genres\":[\"Action\",\"Drama\",\"Science Fiction\"],\"tvdbId\":362250,\"monitored\":true,\"tvRageId\":0,\"overview\":\"All of the men are dead. But one. Based on DC Comics' acclaimed series, Y: The Last Man traverses a post-apocalyptic world in which a cataclysmic event has decimated every male save for one lone human. The new world order of women will explore gender, race, class and survival.\",\"airTime\":\"00:00\",\"seasonCount\":1,\"title\":\"Y: The Last Man\",\"year\":2021,\"rootFolderPath\":\"Z:\\\\Shows\\\\\",\"seasons\":[{\"seasonNumber\":1,\"monitored\":true}],\"status\":\"continuing\",\"certification\":\"TV-MA\",\"runtime\":54,\"seriesType\":\"standard\",\"remotePoster\":\"https://artworks.thetvdb.com/banners/v4/series/362250/posters/611f995929dd5.jpg\",\"profileId\":null,\"addOptions\":{\"ignoreEpisodesWithFiles\":true,\"searchForMissingEpisodes\":true},\"tvMazeId\":42668,\"network\":\"Hulu\",\"useSceneNumbering\":false,\"ratings\":{\"votes\":0,\"value\":0.0},\"titleSlug\":\"y-the-last-man\"}", :scheme :http, :async? true, :request-method :post}, :http-client #object[jdk.internal.net.http.HttpClientFacade 0x3c68460b "jdk.internal.net.http.HttpClientImpl@ddce97d(4)"], :headers {"cache-control" "no-cache, no-store, must-revalidate, max-age=0", "content-type" "application/json; charset=utf-8", "date" "Fri, 24 Sep 2021 16:49:16 GMT", "expires" "0", "pragma" "no-cache", "server" "Microsoft-HTTPAPI/2.0", "transfer-encoding" "chunked", "x-application-version" "3.0.6.1265"}, :status 400, :content-type :application/json, :uri "http://localhost:8989/api/series", :content-type-params {:charset "utf-8"}, :version :http-1.1, :body "[\r\n  {\r\n    \"propertyName\": \"ProfileId\",\r\n    \"errorMessage\": \"'Profile Id' must be greater than '0'.\",\r\n    \"attemptedValue\": 0,\r\n    \"severity\": \"error\",\r\n    \"errorCode\": \"GreaterThanValidator\",\r\n    \"formattedMessageArguments\": [],\r\n    \"formattedMessagePlaceholderValues\": {\r\n      \"comparisonValue\": 0,\r\n      \"comparisonProperty\": \"\",\r\n      \"propertyName\": \"Profile Id\",\r\n      \"propertyValue\": 0\r\n    },\r\n    \"resourceName\": \"GreaterThanValidator\"\r\n  },\r\n  {\r\n    \"propertyName\": \"ProfileId\",\r\n    \"errorMessage\": \"QualityProfile does not exist\",\r\n    \"attemptedValue\": 0,\r\n    \"severity\": \"error\",\r\n    \"errorCode\": \"ProfileExistsValidator\",\r\n    \"formattedMessageArguments\": [],\r\n    \"formattedMessagePlaceholderValues\": {\r\n      \"propertyName\": \"Profile Id\",\r\n      \"propertyValue\": 0\r\n    }\r\n  }\r\n]"}
        at doplarr.interaction_state_machine$fn__19144$fn__19212$state_machine__8301__auto____19219$fn__19221$inst_19197__19238.invoke(interaction_state_machine.clj:129)
        at fmnoise.flow$fn__10996.invokeStatic(flow.cljc:23)
        at fmnoise.flow$fn__10996.invoke(flow.cljc:10)
        at fmnoise.flow$fn__10945$G__10938__10952.invoke(flow.cljc:4)
        at fmnoise.flow$else.invokeStatic(flow.cljc:125)
        at fmnoise.flow$else.invoke(flow.cljc:122)
        at doplarr.interaction_state_machine$fn__19144$fn__19212$state_machine__8301__auto____19219$fn__19221.invoke(interaction_state_machine.clj:106)
        at doplarr.interaction_state_machine$fn__19144$fn__19212$state_machine__8301__auto____19219.invoke(interaction_state_machine.clj:106)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__8319.invoke(ioc_macros.clj:991)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__3152$fn__3153.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__3055$fn__3056.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kiranshila** [comment]
Stale
